import {accountConfig as config} from './config.js';
import {cards,compare,meaning} from './engine.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,act,id='')=>`<button class="btn secondary" type="button" data-account="${act}" data-id="${esc(id)}">${label}</button>`;
let client,user,rows=[],shares=[],orders=[],profile,selected=[],bridge,busy=false;
const dialog=document.createElement('dialog');dialog.id='account-dialog';dialog.setAttribute('aria-labelledby','account-title');document.body.append(dialog);
const configured=config.accountsEnabled===true&&!!config.supabaseUrl&&!!config.publishableKey;
const check=r=>{if(r.error)throw Error(r.error.message);return r.data;};
function show(html){dialog.innerHTML=`<div class="account-shell"><div class="row space-between"><h2 id="account-title">Your tarot account</h2>${btn('Close','close')}</div><p id="account-message" role="status"></p>${html}</div>`;if(!dialog.open)dialog.showModal();}
function message(text){const el=dialog.querySelector('#account-message');if(el)el.textContent=text;}
async function api(body){const expectedUser=user?.id;const {data:{session}}=await client.auth.getSession();if(!session)throw Error('Sign in first');const r=await fetch(config.supabaseUrl+'/functions/v1/tarot-api',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(user?.id!==expectedUser)throw Error('Your account changed. Reopen your account.');if(!r.ok)throw Error(result.error||'Unable to connect');return result;}
async function init(){if(client)return;if(!configured)throw Error('Accounts are being connected. Your free local journal still works.');const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.57.4');client=createClient(config.supabaseUrl,config.publishableKey);const r=await client.auth.getUser();user=r.data.user;client.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(!user){rows=[];shares=[];orders=[];profile=null;selected=[];if(dialog.open)login();}});}
function login(){show(`<p>Save private cloud readings and share chosen readings with other accounts.</p><form id="account-login"><label>Email<input name="email" type="email" autocomplete="email" required></label><button class="btn">Send sign-in code</button></form><form id="account-verify"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Code from your email<input name="token" inputmode="numeric" autocomplete="one-time-code" required></label><button class="btn">Sign in</button></form>`);}
function summary(r){return `<strong>${esc(r.spread)}</strong><p>${r.cards.map(c=>esc(cards.find(x=>x.id===c.id)?.name||c.id)+(c.reversed?' ↧':'')).join(' · ')}</p>`;}
function option(r,type){return `<article class="panel account-reading">${summary(r.payload)}<label><input type="checkbox" data-cloud-select="${type}:${r.id}" ${selected.includes(type+':'+r.id)?'checked':''}> Select for comparison</label><div class="row">${btn('Open',type==='own'?'open-own':'open-share',r.id)}${type==='own'?btn('Share','share',r.id):''}${type==='share'&&r.owner_id===user?.id?btn('Revoke share','revoke',r.id):''}</div>${type==='share'?`<small>${r.recipient_id?'Shared privately':'Public snapshot'} · AI ${r.allow_ai?'allowed':'not allowed'}</small>`:''}</article>`;}
async function dashboard(){await init();if(!user)return login();const uid=user.id;const results=await Promise.all([client.from('tarot_profiles').select('*').eq('id',uid).maybeSingle(),client.from('tarot_readings').select('*').eq('owner_id',uid).order('updated_at',{ascending:false}),client.from('tarot_shares').select('*').or(`owner_id.eq.${uid},recipient_id.eq.${uid}`).order('created_at',{ascending:false}),client.from('tarot_orders').select('id,kind,status,created_at').eq('owner_id',uid).order('created_at',{ascending:false}).limit(30)]);if(user?.id!==uid)return;[profile,rows,shares,orders]=results.map(check);selected=selected.filter(k=>[...rows.map(r=>'own:'+r.id),...shares.map(r=>'share:'+r.id)].includes(k));
show(`<p>Account ID: <code class="account-id">${esc(uid)}</code></p>${btn('Sign out','logout')}<form id="profile-form"><h3>Your profile</h3><label>Username<input name="username" pattern="[a-z0-9_]{3,24}" minlength="3" maxlength="24" value="${esc(profile?.username)}" required></label><label>Display name<input name="display_name" maxlength="80" value="${esc(profile?.display_name)}"></label><label>Bio<textarea name="bio" maxlength="500">${esc(profile?.bio)}</textarea></label><label><input name="is_public" type="checkbox" ${profile?.is_public?'checked':''}> Make my profile public</label><button class="btn">Save profile</button></form>${profile?.is_public?`<label>Your profile link<input readonly value="${esc(location.origin+location.pathname+'?profile='+profile.username)}"></label>`:''}<h3>Private cloud journal</h3><p>Save individual device readings below. Cloud copies stay private until you share a snapshot. Saving again updates that copy; cloud copies never overwrite this device’s journal.</p><div class="row">${btn('Refresh','dashboard')}${btn('Compare selected','compare')}${btn('Paid AI comparison','ai-pair')}</div>${rows.map(r=>option(r,'own')).join('')||'<p>No cloud readings yet.</p>'}<h3>On this device</h3><p>Choose which readings to copy into this account. Saved questions and notes remain private and are never sent to AI.</p>${bridge.readings().map(r=>`<article class="panel account-reading">${summary(r)}${btn('Save private cloud copy','upload',r.id)}</article>`).join('')||'<p>Draw a reading first.</p>'}<h3>Shared readings</h3>${shares.map(r=>option(r,'share')).join('')||'<p>No shared readings yet.</p>'}<form id="find-profile"><label>Find a public profile<input name="username" pattern="[a-z0-9_]{3,24}" required></label><button class="btn">View profile</button></form><h3>Purchased AI reports</h3><p>Return here after checkout, even if you closed the payment page. A failed report can be retried without a new purchase.</p>${orders.map(o=>`<p>${esc(o.kind)} · ${esc(o.status)} ${btn('Open / retry','report',o.id)}</p>`).join('')||'<p>No purchases yet.</p>'}`);}
async function publicProfile(name){await init();const p=check(await client.from('tarot_profiles').select('*').eq('username',name).eq('is_public',true).single());const list=check(await client.from('tarot_shares').select('*').eq('owner_id',p.id).is('recipient_id',null));shares=[...shares.filter(s=>!list.some(t=>t.id===s.id)),...list];show(`<h3>${esc(p.display_name||p.username)}</h3><p>@${esc(p.username)}</p><p>${esc(p.bio)}</p><p>Only explicitly public readings appear here.</p>${list.map(r=>option(r,'share')).join('')}${btn('Compare selected','compare')}${btn('Paid AI comparison','ai-pair')}${btn('My account','dashboard')}`);}
function chosen(){if(selected.length!==2)throw Error('Select exactly two readings');return selected.map(key=>{const [type,id]=key.split(':');const r=(type==='own'?rows:shares).find(x=>x.id===id);if(!r)throw Error('Refresh and select readings again');return {type,id,payload:r.payload};});}
function detail(r,own){show(`${summary(r.payload)}${r.payload.cards.map((c,i)=>`<section><h3>${esc(r.payload.positions[i])}</h3><p>${esc(cards.find(x=>x.id===c.id)?.name)} · ${c.reversed?'Reversed':'Upright'}</p><p>${esc(meaning(c))}</p></section>`).join('')}${own?`<h3>Private question</h3><p>${esc(r.payload.question)}</p><h3>Private notes</h3><p>${esc(r.payload.notes)}</p>${btn('Paid in-depth interpretation','ai-one',r.id)}`:''}${btn('Back to account','dashboard')}`);}
async function paywall(refs){if(!user)throw Error('Sign in to purchase a report');const kind=refs.length===2?'comparison':'interpretation';const quote=await api({action:'quote',kind});const amount=new Intl.NumberFormat(undefined,{style:'currency',currency:quote.currency}).format(quote.amount/(10**new Intl.NumberFormat(undefined,{style:'currency',currency:quote.currency}).resolvedOptions().maximumFractionDigits));show(`<h3>${kind==='comparison'?'Compare two readings with AI':'An in-depth AI interpretation'}</h3><p>One-time purchase: <strong>${esc(amount)}</strong>. No subscription.</p><p>Explore card positions, reversals, themes, and reflection prompts${kind==='comparison'?', including similarities and differences between both readings':''}.</p><p>Only cards, spread positions, deck, and reading date are sent to OpenAI. Private questions and notes are excluded. AI reflections can be mistaken and are not predictions.</p><form id="checkout-form"><label><input name="consent" type="checkbox" required> I agree to send these readings to OpenAI for this report.</label><button class="btn">Continue to secure checkout · ${esc(amount)}</button></form>${btn('Back','dashboard')}`);dialog.querySelector('#checkout-form').onsubmit=e=>run(e,async()=>{const result=await api({action:'checkout',kind,refs:refs.map(({type,id})=>({type,id})),priceId:quote.priceId,consent:true});if(new URL(result.url).hostname!=='checkout.stripe.com')throw Error('Unexpected checkout URL');location.assign(result.url);});}
async function run(e,fn){e?.preventDefault();if(busy)return;busy=true;dialog.setAttribute('aria-busy','true');message('Working…');try{await fn();message('');}catch(err){message(err.message||'Unable to complete this action');}finally{busy=false;dialog.removeAttribute('aria-busy');}}
dialog.addEventListener('change',e=>{const k=e.target.dataset.cloudSelect;if(!k)return;if(e.target.checked){if(selected.length===2){e.target.checked=false;message('Choose at most two readings');return;}selected.push(k);}else selected=selected.filter(x=>x!==k);});
dialog.addEventListener('click',e=>{const b=e.target.closest('[data-account]');if(!b)return;if(b.dataset.account==='close'){dialog.close();return;}run(e,async()=>{const id=b.dataset.id;switch(b.dataset.account){
case 'dashboard':return dashboard();
case 'logout':check(await client.auth.signOut());user=null;rows=[];shares=[];orders=[];selected=[];return login();
case 'upload':{const r=bridge.readings().find(r=>r.id===id);if(!r)throw Error('Reading no longer available');check(await client.from('tarot_readings').upsert({owner_id:user.id,local_id:r.id,payload:r,updated_at:new Date().toISOString()},{onConflict:'owner_id,local_id'}));return dashboard();}
case 'open-own':return detail(rows.find(r=>r.id===id),true);
case 'open-share':return detail(shares.find(r=>r.id===id),false);
case 'revoke':check(await client.from('tarot_shares').delete().eq('id',id).eq('owner_id',user.id));return dashboard();
case 'share':show(`<h3>Share a reading snapshot</h3><p>Questions and notes are excluded. Revoking a share stops future access but cannot recall saved copies or purchased reports.</p><form id="share-form" data-id="${esc(id)}"><label>Who can see it?<select name="visibility"><option value="recipient">One account</option><option value="public">Anyone (public)</option></select></label><label>Recipient username (for one account)<input name="username" pattern="[a-z0-9_]{3,24}"></label><label><input name="allowAI" type="checkbox"> Allow recipients to purchase an AI comparison using this snapshot</label><button class="btn">Create share</button></form>${btn('Back','dashboard')}`);return;
case 'ai-one':return paywall([{type:'own',id}]);
case 'ai-pair':return paywall(chosen());
case 'compare':{const pair=chosen();const stats=compare(pair[0].payload,pair[1].payload);show(`<h3>Two readings, side by side</h3><p>${stats.common.length?'Cards in common: '+stats.common.map(esc).join(', '):'No cards in common.'}</p><p>${stats.samePositions?'Matching spread positions.':'Different spreads: compare themes rather than equating positions.'}</p>${pair.map(r=>`<section class="panel">${summary(r.payload)}${r.payload.cards.map((c,i)=>`<p>${esc(r.payload.positions[i])}: ${esc(cards.find(x=>x.id===c.id)?.name)} ${c.reversed?'(reversed)':''}</p>`).join('')}</section>`).join('')}${btn('Paid AI comparison','ai-pair')}${btn('Back','dashboard')}`);return;}
case 'report':{const result=await api({action:'report',orderId:id});show(`<h3>Your AI reflection</h3><p>Order: ${esc(id)}</p><div class="ai-report">${esc(result.report)}</div>${btn('Back to account','dashboard')}`);return;}
}});});
dialog.addEventListener('submit',e=>{if(e.target.id==='checkout-form')return;run(e,async()=>{const f=e.target;const values=Object.fromEntries(new FormData(f));switch(f.id){
case 'account-login':check(await client.auth.signInWithOtp({email:values.email,options:{shouldCreateUser:true}}));show(`<p>Check your email for your sign-in code.</p><form id="account-verify"><input name="email" type="hidden" value="${esc(values.email)}"><label>Email code<input name="token" inputmode="numeric" autocomplete="one-time-code" required></label><button class="btn">Sign in</button></form>`);return;
case 'account-verify':{const r=check(await client.auth.verifyOtp({email:values.email,token:values.token,type:'email'}));user=r.user;return dashboard();}
case 'profile-form':check(await client.from('tarot_profiles').upsert({id:user.id,username:values.username,display_name:values.display_name,bio:values.bio,is_public:values.is_public==='on'}));return dashboard();
case 'share-form':if(values.visibility==='recipient'&&!values.username)throw Error('Enter a recipient username');const r=await api({action:'share',readingId:f.dataset.id,username:values.visibility==='recipient'?values.username:null,public:values.visibility==='public',allowAI:values.allowAI==='on'});show(`<h3>Reading shared</h3><p>${values.visibility==='public'?'Anyone with this link can view the snapshot.':'Only the recipient and you can open this link.'}</p><label>Share link<input readonly value="${esc(location.origin+location.pathname+'?share='+r.id)}"></label>${btn('Back','dashboard')}`);return;
case 'find-profile':return publicProfile(values.username);
}});});
export function installAccounts(appBridge){bridge=appBridge;const button=document.createElement('button');button.type='button';button.className='btn secondary account-open';button.textContent='Account & sharing';document.querySelector('.site-header').append(button);button.addEventListener('click',()=>{show('<p>Opening your account…</p>');run(null,dashboard);});const query=new URLSearchParams(location.search);if(query.has('profile')||query.has('share')||query.has('order')){show('<p>Opening shared content…</p>');run(null,async()=>{await init();if(query.has('profile'))return publicProfile(query.get('profile'));if(query.has('share')){const result=await client.from('tarot_shares').select('*').eq('id',query.get('share')).single();if(result.error&&!user)return login();const r=check(result);return detail(r,false);}if(!user)return login();return dashboard();});}}
