import {cards,presets,localDate,makeReading,meaning,shareText,compare} from './engine.js';

const KEY='tarot-studio-web-v1';
import { deckCatalog } from './deck-catalog.js';
const themeNames=['MDSN','Minimalist Botanical','Rider-Waite','Botanical','Midnight','Patchwork'];
const assetUrl=path=>new URL(path,import.meta.url).href;
const cardBackUrl=assetUrl('./card-back.webp');
const app=document.querySelector('#app'),nav=document.querySelector('#navigation'),modal=document.querySelector('#modal');
const initial=()=>({version:1,deck:'Minimalist Botanical',reversals:true,readings:[],spreads:[],daily:{}});
let data=initial(),storageError=false,activeDay=localDate(),view='today',readingId=null,selected=[],search='',builder={name:'My spread',positions:['What to notice','What to try']},draftNotes='',dirty=false,toastTimer;
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iconPaths={today:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',spreads:'<rect x="3" y="6" width="7" height="13" rx="1.5"/><rect x="14" y="3" width="7" height="13" rx="1.5"/>',guide:'<path d="M12 5v15M12 5C8 2 3 4 3 4v15s5-2 9 1c4-3 9-1 9-1V4s-5-2-9 1z"/>',journal:'<path d="M5 3h14v18H5zM8 7h8M8 11h8M8 15h5"/>',decks:'<rect x="7" y="3" width="13" height="17" rx="2"/><path d="M4 6v15h12M10 8h7m-7 4h7"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',back:'<path d="M19 12H5m5-5-5 5 5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',up:'<path d="m6 14 6-6 6 6"/>',down:'<path d="m6 10 6 6 6-6"/>',share:'<path d="M12 15V3m-4 4 4-4 4 4M5 11v9h14v-9"/>',check:'<path d="m5 12 4 4L19 6"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||iconPaths.today}</svg>`;
const button=(text,action,value='',cls='',extra='')=>`<button type="button" class="btn ${cls}" data-action="${action}" data-value="${escape(value)}" ${extra}>${text}</button>`;
const cardById=id=>cards.find(c=>c.id===id);
const formatDate=d=>new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const reading=()=>data.readings.find(r=>r.id===readingId);

function validReading(r){return r&&typeof r.id==='string'&&typeof r.spread==='string'&&typeof r.date==='string'&&!Number.isNaN(Date.parse(r.date))&&themeNames.includes(r.deck)&&Array.isArray(r.positions)&&r.positions.length>0&&r.positions.length<=10&&r.positions.every(p=>typeof p==='string')&&Array.isArray(r.cards)&&r.cards.length===r.positions.length&&r.cards.every(p=>cardById(p.id)&&typeof p.reversed==='boolean')&&typeof r.notes==='string'&&typeof r.question==='string';}
function validData(d){return d&&themeNames.includes(d.deck)&&typeof d.reversals==='boolean'&&Array.isArray(d.readings)&&d.readings.every(validReading)&&Array.isArray(d.spreads)&&d.spreads.every(s=>typeof s.id==='string'&&typeof s.name==='string'&&Array.isArray(s.positions)&&s.positions.length>0&&s.positions.length<=10&&s.positions.every(p=>typeof p==='string'&&p.trim()))&&d.daily&&typeof d.daily==='object'&&!Array.isArray(d.daily)&&Object.values(d.daily).every(validReading);}
function load(){try{const raw=localStorage.getItem(KEY);const next=raw?JSON.parse(raw):initial();if(!validData(next))throw Error('Unreadable journal');data=next;storageError=false;}catch{storageError=true;}}
function commit(change){if(storageError){toast('Your journal could not be loaded. Retry before saving.');return false;}try{const next=change(data);if(!validData(next))throw Error('Invalid reading');localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch{toast('Could not save. Check browser storage and try again.');return false;}}
function toast(message){clearTimeout(toastTimer);const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),4200);}
function symbolicFace(pull,deck='Botanical'){const c=cardById(pull.id),number=c.id.startsWith('major-')?Number(c.id.split('-')[1]):c.suit;return `<div class="card-face ${deck.toLowerCase().replace(/[^a-z]/g,'')} ${pull.reversed?'reversed':''}" aria-label="${escape(c.name)}${pull.reversed?', reversed':''}"><span class="face-number">${escape(number)}</span><span class="face-symbol" aria-hidden="true">${c.symbol}</span><div><div class="face-name">${escape(c.name)}</div><div class="face-orientation">${pull.reversed?'Reversed':'Upright'}</div></div></div>`;}
function face(pull,deck='Botanical') {
  const c=cardById(pull.id),image=deckCatalog[deck]?.images[c.legacyId];
  if(!image) return symbolicFace(pull,deck);
  return `<div class="illustrated-card ${pull.reversed?'reversed':''}"><img src="${escape(assetUrl(image))}" alt="${escape(c.name)}${pull.reversed?', reversed':''}" loading="lazy" decoding="async" width="400" height="600"><span class="illustrated-label">${escape(c.name)} · ${pull.reversed?'Reversed':'Upright'}</span></div>`;
}

function head(title,eyebrow,action=''){return `<div class="page-heading"><div>${eyebrow?`<p class="eyebrow">${eyebrow}</p>`:''}<h1>${title}</h1></div>${action}</div>`;}
function navigate(to,options={}){if(dirty&&!confirm('Leave without saving your reflection?'))return false;dirty=false;readingId=null;view=to;location.hash=to;render();if(!options.keepScroll){window.scrollTo({top:0,behavior:'instant'});app.focus({preventScroll:true});}return true;}
function openReading(id){const r=data.readings.find(x=>x.id===id);if(!r)return;if(dirty&&!confirm('Leave without saving your reflection?'))return;readingId=id;draftNotes=r.notes;dirty=false;view='reading';render();window.scrollTo({top:0,behavior:'instant'});app.focus({preventScroll:true});}
function dailyPull(){activeDay=localDate();const existing=data.daily[activeDay];if(existing){openReading(existing.id);return existing.id;}const r=makeReading({name:'Daily card',positions:['Today’s reflection']},data.deck,data.reversals);if(commit(d=>({...d,daily:{...d.daily,[activeDay]:r},readings:[r,...d.readings]}))){render();toast('Your daily card is saved in your journal.');return r.id;}return null;}
function saveNotes(){const r=reading();if(!r)return false;const next={...r,notes:draftNotes};if(commit(d=>({...d,readings:d.readings.map(x=>x.id===r.id?next:x),daily:Object.fromEntries(Object.entries(d.daily).map(([date,x])=>[date,x.id===r.id?next:x]))}))){dirty=false;const status=document.querySelector('#note-status');if(status)status.textContent='Saved on this browser';toast('Reflection saved.');return true;}return false;}

function todayView(){const r=data.daily[localDate()],c=r?cardById(r.cards[0].id):null;return head('Your daily ritual','TODAY',`<p class="muted">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p>`)+`<section class="daily-layout"><div class="card-stage">${r?face(r.cards[0],r.deck):`<button class="card-back" data-action="daily" aria-label="Reveal your daily tarot card"><img src="${escape(cardBackUrl)}" width="540" height="810" alt="Gold star and botanical ornament on a plum tarot card back"></button>`}<span class="stage-caption">${r?'A card to carry with you':'A little space for possibility'}</span></div><div class="daily-copy"><span class="pill">${r?'Your card for today':'One card · A fresh perspective'}</span><h2>${r?escape(c.name):'What will you notice today?'}</h2>${r?`<p class="keywords">${escape(c.keywords)}</p><p class="lead">${escape(meaning(r.cards[0]).split('\n\n').slice(-1)[0])}</p>${button(`Reflect on this card ${icon('arrow')}`,'open',r.id)}`:`<p class="lead">Take a breath. Bring a question, or simply see what meets you here.</p>${button(`Reveal my card ${icon('arrow')}`,'daily')}`}<div class="small-rule"></div><p class="note">${r?'Your card stays with you for the day. Come back whenever you need a moment to reflect.':'Draw once a day. Your card and reflections will be saved in your journal.'}</p></div></section><div class="section-bar"><h2>Go a little deeper</h2>${button('All spreads →','navigate','spreads','text')}</div><div class="quick-grid">${[{name:'Past · Present · Future',copy:'Step back and see the bigger picture.',id:'timeline'},{name:'Creative unblock',copy:'Find the spark and what feeds it.',id:'creative'},{name:'Build your own',copy:'Make space for your own questions.',id:'builder'}].map((s,i)=>`<button class="quick-card" data-action="${i===2?'navigate':'choose-spread'}" data-value="${s.id}"><div class="quick-title"><h3>${s.name}</h3>${icon(i===2?'plus':'spreads')}</div><p>${s.copy}</p></button>`).join('')}</div>`;}
function spreadsView(){return head('A spread for the moment','SPREADS',button(`${icon('plus')} Build a spread`,'navigate','builder','secondary'))+`<div class="grid">${[...presets,...data.spreads].map(s=>`<article class="panel spread-panel"><div class="spread-glyph" aria-hidden="true">${s.positions.slice(0,5).map((_,i)=>`<span class="mini-back">${i+1}</span>`).join('')}</div><div><p class="eyebrow">${s.positions.length} CARDS${s.id.startsWith('custom-')?' · YOUR SPREAD':''}</p><h2>${escape(s.name)}</h2></div><ol>${s.positions.map(p=>`<li>${escape(p)}</li>`).join('')}</ol>${button('Use this spread →','choose-spread',s.id,'secondary full')}</article>`).join('')}</div>`;}
function builderView(){return button(`${icon('back')} Spreads`,'navigate','spreads','text back-link')+head('Make it your own','SPREAD BUILDER')+`<form id="builder-form" class="builder"><div class="field"><label class="field-label" for="spread-name">Spread name</label><input id="spread-name" data-field="builder-name" maxlength="80" required value="${escape(builder.name)}" placeholder="A name for your spread"></div><div class="section-bar"><h2>Card positions</h2><span class="muted">${builder.positions.length} of 10</span></div><p class="muted">Give each card a question or role. The order here is the order you’ll draw.</p>${builder.positions.map((p,i)=>`<div class="position-editor"><span class="position-number">${i+1}</span><input aria-label="Position ${i+1}" data-field="position" data-index="${i}" maxlength="100" required value="${escape(p)}" placeholder="What should this card explore?"><div class="position-controls"><button type="button" class="icon-btn" data-action="position-up" data-value="${i}" aria-label="Move position ${i+1} up" ${i===0?'disabled':''}>${icon('up')}</button><button type="button" class="icon-btn" data-action="position-down" data-value="${i}" aria-label="Move position ${i+1} down" ${i===builder.positions.length-1?'disabled':''}>${icon('down')}</button><button type="button" class="icon-btn" data-action="position-remove" data-value="${i}" aria-label="Remove position ${i+1}" ${builder.positions.length===1?'disabled':''}>${icon('close')}</button></div></div>`).join('')}<div class="row space-between">${button(`${icon('plus')} Add position`,'position-add','','secondary',builder.positions.length===10?'disabled':'')}<button class="btn" type="submit">Save spread ${icon('check')}</button></div></form>`;}
function guideEntries(query){const found=cards.filter(c=>`${c.name} ${c.keywords}`.toLowerCase().includes(query.toLowerCase()));return found.length?found.map(c=>`<details class="guide-entry"><summary><div><h3>${escape(c.name)}</h3><p class="muted">${escape(c.suit)}</p></div>${icon('plus')}</summary><p class="keywords">${escape(c.keywords)}</p><p><strong>Upright</strong><br>${escape(c.upright)}</p><p><strong>Reversed</strong><br>${escape(c.reversed)}</p></details>`).join(''):`<div class="empty"><h2>No cards found</h2><p>Try a card name, a suit, or a theme like “creativity.”</p></div>`;}
function guideView(){return head('Get to know the cards','THE GUIDE')+`<div class="search-row"><label class="field-label" for="guide-search">Find a card</label><input type="search" id="guide-search" data-field="search" value="${escape(search)}" placeholder="Try The Star, Cups, or creativity" aria-controls="guide-results"></div><p class="quiet-banner">78 cards, upright and reversed. Explore the full written guide and bring your own perspective.</p><div class="guide-list" id="guide-results">${guideEntries(search)}</div><p class="quiet-banner">Written interpretations offer perspective and reflection, not certainty.</p>`;}
function journalView(){return head('Your moments, collected','JOURNAL')+`<div class="journal-tools"><p class="muted">${data.readings.length} saved ${data.readings.length===1?'reading':'readings'} · Stored in this browser</p>${button(`Compare selected (${selected.length}/2)`,'compare','','secondary',selected.length!==2?'disabled':'')}</div>${data.readings.length?`<div class="journal-list">${data.readings.map(r=>`<article class="panel journal-card ${selected.includes(r.id)?'selected':''}"><div><p class="eyebrow">${formatDate(r.date)} · ${escape(r.deck)}</p><h2>${escape(r.spread)}</h2></div><p class="card-names">${r.cards.map(p=>escape(cardById(p.id).name)+(p.reversed?' ↧':'')).join(' · ')}</p><div class="row space-between">${button('Open reading →','open',r.id,'text')}<label class="check-label"><input type="checkbox" data-field="select-reading" value="${escape(r.id)}" ${selected.includes(r.id)?'checked':''}>Compare</label></div></article>`).join('')}</div>`:`<section class="empty"><span aria-hidden="true">✧</span><h2>Your story starts with a card</h2><p>Draw a daily card or try a spread. Your readings and reflections will find their home here.</p>${button('Pull today’s card','navigate','today')}</section>`}<p class="quiet-banner">Readings stay on this device and browser. Clearing browser data can remove them. Account sharing and sync aren’t connected yet.</p>`;}
function readingView(){const r=reading();if(!r)return journalView();return button(`${icon('back')} Journal`,'navigate','journal','text back-link')+head(escape(r.spread),`${formatDate(r.date)} · ${escape(r.deck)}`,button(icon('share')+' Share','share',r.id,'secondary'))+`${r.question?`<p class="reading-question">${escape(r.question)}</p>`:''}<div class="reading-grid ${r.cards.length===1?'single':''}">${r.cards.map((p,i)=>`<article class="reading-item">${r.cards.length===1?face(p,r.deck):''}<p class="eyebrow">${i+1} · ${escape(r.positions[i])}</p>${r.cards.length!==1?face(p,r.deck):''}<h3>${escape(cardById(p.id).name)}</h3><p class="keywords">${escape(cardById(p.id).keywords)}</p><p>${escape(meaning(p))}</p></article>`).join('')}</div><div class="panel builder"><div class="section-bar" style="margin-top:0"><h2>Your perspective</h2><span class="muted" id="note-status">${dirty?'Unsaved changes':'Private reflection'}</span></div><label class="field-label" for="reading-notes">What resonates? What do you see differently?</label><textarea id="reading-notes" data-field="notes" placeholder="Leave a little note for your future self…">${escape(draftNotes)}</textarea><div class="row space-between" style="margin-top:15px"><p class="muted">Your question and notes aren’t included when sharing.</p>${button('Save reflection','save-notes')}</div></div><div class="quiet-banner">Expanded interpretations will be an optional paid feature. This version uses written guidance only.</div>`;}
function compareView(){const pair=selected.map(id=>data.readings.find(r=>r.id===id)).filter(Boolean);if(pair.length!==2)return journalView();const stats=compare(...pair);return button(`${icon('back')} Journal`,'navigate','journal','text back-link')+head('Two perspectives','COMPARE READINGS')+`<div class="notice"><strong>${stats.common.length?'Cards in common: '+stats.common.map(escape).join(', '):'A different set of cards in each reading.'}</strong><br>${stats.samePositions?'The same spread positions make it easier to notice what changed.':'These spreads have different positions. Compare cards and suit counts rather than treating their positions as equivalent.'}</div><div class="comparison-grid">${pair.map((r,j)=>`<section class="panel"><p class="eyebrow">${j?'SECOND':'FIRST'} READING · ${formatDate(r.date)}</p><h2>${escape(r.spread)}</h2>${r.cards.map((p,i)=>`<div class="comparison-entry"><p class="position-label">${i+1} · ${escape(r.positions[i])}</p><h3>${escape(cardById(p.id).name)}</h3><p>${p.reversed?'Reversed':'Upright'} · ${escape(meaning(p))}</p></div>`).join('')}<div class="suit-list">${Object.entries(j?stats.suitsB:stats.suitsA).map(([s,n])=>`<span>${escape(s)} · ${n}</span>`).join('')}</div></section>`).join('')}</div><p class="quiet-banner">You’re comparing two readings from your own journal. Cross-account comparisons are planned.</p>`;}
function decksView(){return head('Set the mood','YOUR DECK')+`<div class="deck-grid">${themeNames.map((name,i)=>`<article class="panel deck-panel ${data.deck===name?'selected':''}"><div class="deck-preview">${face({id:'major-17',reversed:false},name)}</div><h3>${name}</h3><p>${({MDSN:'Your original illustrated deck. One missing card uses a labeled fallback.','Minimalist Botanical':'A full deck of botanical illustrations.','Rider-Waite':'The familiar illustrated tarot deck.',Botanical:'A simple symbolic parchment theme.',Midnight:'A symbolic theme in deep plum.',Patchwork:'A symbolic theme in soft rose.'})[name]}</p>${button(data.deck===name?icon('check')+' Selected':'Choose theme','choose-deck',name,data.deck===name?'full':'secondary full')}</article>`).join('')}</div><p class="quiet-banner">Choose an illustrated deck or a simple symbolic theme. Previous readings keep the deck you used to draw them.</p><div class="settings-line"><div><h3>Include reversed cards</h3><p>Let cards appear upright or reversed in future draws.</p></div><label class="switch"><input type="checkbox" data-field="reversals" aria-label="Include reversed cards" role="switch" ${data.reversals?'checked':''}></label></div>`;}
function render(){const active=view==='builder'?'spreads':['reading','compare'].includes(view)?'journal':view;nav.className='nav';nav.innerHTML=['today','spreads','guide','journal','decks'].map(t=>`<a href="#${t}" data-action="navigate" data-value="${t}" class="${active===t?'active':''}" ${active===t?'aria-current="page"':''}>${icon(t)}<span>${t[0].toUpperCase()+t.slice(1)}</span></a>`).join('');document.querySelector('#deck-label').textContent=data.deck;document.title=`Tarot Studio — ${view==='reading'?'Your reading':view[0].toUpperCase()+view.slice(1)}`;if(storageError){app.innerHTML=`<section class="empty"><h1>Your journal couldn’t be opened</h1><p>Your stored data hasn’t been cleared. Check that browser storage is available, then try again.</p>${button('Try again','retry')}</section>`;return;}const views={today:todayView,spreads:spreadsView,builder:builderView,guide:guideView,journal:journalView,reading:readingView,compare:compareView,decks:decksView};app.innerHTML=`<div class="fade-in">${(views[view]||todayView)()}</div>`;}
function chooseSpread(id){const sp=[...presets,...data.spreads].find(s=>s.id===id);if(!sp)return;modal.innerHTML=`<form id="draw-form" data-spread="${escape(id)}"><div class="modal-head"><div><p class="eyebrow">${sp.positions.length} CARDS · ${escape(data.deck)}</p><h2 id="modal-title">${escape(sp.name)}</h2></div><button type="button" class="icon-btn" data-action="close-modal" aria-label="Close">${icon('close')}</button></div><p class="muted">Bring a question, or leave this open and see what comes up.</p><label class="field-label" for="reading-question">Your question <span class="muted">(optional)</span></label><textarea id="reading-question" name="question" maxlength="2000" placeholder="What would I like a little clarity on?"></textarea><p class="muted" style="margin-top:10px">Your question is private and stays out of shared summaries.</p><button type="submit" class="btn full">Draw ${sp.positions.length} cards ${icon('arrow')}</button></form>`;modal.showModal();}
async function shareReading(id){const r=data.readings.find(x=>x.id===id);if(!r)return;const text=shareText(r);try{if(navigator.share){await navigator.share({title:r.spread,text});return;}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);toast('Card summary copied. Private notes weren’t included.');return;}}catch(e){if(e.name==='AbortError')return;}modal.innerHTML=`<div class="modal-head"><h2 id="modal-title">Share your cards</h2><button class="icon-btn" data-action="close-modal" aria-label="Close">${icon('close')}</button></div><p class="muted">Copy this summary. Your private question and notes are not included.</p><textarea readonly id="share-summary" aria-label="Card summary">${escape(text)}</textarea>`;modal.showModal();document.querySelector('#share-summary').select();}
function saveSpread(){if(!builder.name.trim()||builder.positions.some(p=>!p.trim())){toast('Name your spread and each position first.');return false;}const sp={id:`custom-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name:builder.name.trim(),positions:builder.positions.map(p=>p.trim())};if(commit(d=>({...d,spreads:[...d.spreads,sp]}))){builder={name:'My spread',positions:['What to notice','What to try']};navigate('spreads');toast('Your custom spread is ready.');return true;}return false;}
document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target)return;e.preventDefault();const action=target.dataset.action,v=target.dataset.value;switch(action){case'navigate':navigate(v);break;case'daily':dailyPull();break;case'open':openReading(v);break;case'choose-spread':chooseSpread(v);break;case'close-modal':modal.close();break;case'save-notes':saveNotes();break;case'share':shareReading(v);break;case'compare':if(selected.length===2){view='compare';render();window.scrollTo({top:0,behavior:'instant'});}break;case'choose-deck':if(themeNames.includes(v)&&commit(d=>({...d,deck:v}))){render();toast(`${v} selected for your next reading.`);}break;case'position-add':if(builder.positions.length<10){builder.positions.push('');render();const fields=app.querySelectorAll('[data-field="position"]');fields[fields.length-1]?.focus();}break;case'position-remove':if(builder.positions.length>1){builder.positions.splice(Number(v),1);render();}break;case'position-up':case'position-down':{const i=Number(v),j=i+(action==='position-up'?-1:1);if(j>=0&&j<builder.positions.length){[builder.positions[i],builder.positions[j]]=[builder.positions[j],builder.positions[i]];render();app.querySelector(`[data-field="position"][data-index="${j}"]`)?.focus();}break;}case'retry':load();render();break;}});
document.addEventListener('input',e=>{const el=e.target;switch(el.dataset.field){case'search':search=el.value;document.querySelector('#guide-results').innerHTML=guideEntries(search);break;case'builder-name':builder.name=el.value;break;case'position':builder.positions[Number(el.dataset.index)]=el.value;break;case'notes':draftNotes=el.value;dirty=draftNotes!==(reading()?.notes||'');document.querySelector('#note-status').textContent=dirty?'Unsaved changes':'Saved on this browser';break;}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.field==='reversals'){if(commit(d=>({...d,reversals:el.checked})))toast(el.checked?'Reversed cards included.':'Only upright cards for future draws.');else el.checked=data.reversals;}if(el.dataset.field==='select-reading'){if(el.checked){if(selected.length===2){el.checked=false;toast('Unselect one reading to choose another.');return;}selected.push(el.value);}else selected=selected.filter(id=>id!==el.value);render();}});
document.addEventListener('submit',e=>{if(e.target.id==='builder-form'){e.preventDefault();saveSpread();}if(e.target.id==='draw-form'){e.preventDefault();const sp=[...presets,...data.spreads].find(s=>s.id===e.target.dataset.spread);if(!sp)return;const q=new FormData(e.target).get('question').toString().trim(),r=makeReading(sp,data.deck,data.reversals,q);if(commit(d=>({...d,readings:[r,...d.readings]}))){modal.close();openReading(r.id);}}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['today','spreads','builder','guide','journal','decks'].includes(next)&&next!==view)navigate(next);});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
// Keep a second open tab from overwriting a more recent journal.
window.addEventListener('storage',e=>{if(e.key===KEY){load();selected=selected.filter(id=>data.readings.some(r=>r.id===id));if(!dirty)render();else toast('The journal changed in another tab. Your draft is still here.');}});
function checkDay(){if(localDate()!==activeDay){activeDay=localDate();if(view==='today')render();}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkDay();});setInterval(checkDay,30000);
load();const start=location.hash.slice(1);if(['today','spreads','builder','guide','journal','decks'].includes(start))view=start;render();

// Feature-detected agent access reuses the same actions and state as the UI.
if(document.modelContext?.registerTool){const lifetime=new AbortController();const context=document.modelContext;const tools=[
{name:'get_tarot_studio_summary',title:'Read tarot studio summary',description:'Read the selected theme and local journal counts, without private notes or questions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');return {deck:data.deck,readingCount:data.readings.length,customSpreadCount:data.spreads.length,hasDailyCard:!!data.daily[localDate()]};}},
{name:'reveal_daily_tarot_card',title:'Reveal today’s tarot card',description:'Draw and save today’s card locally, or open the existing daily reading without drawing again.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');if(dirty)throw Error('Save the current reflection before drawing.');view='today';readingId=null;const id=dailyPull();if(!id)throw Error('Could not save the daily card.');const r=data.readings.find(x=>x.id===id);return {readingId:id,card:cardById(r.cards[0].id).name,reversed:r.cards[0].reversed};}}
];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});}
