import {Window} from 'happy-dom';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {cards,compare,meaning} from '../tarot-studio/engine.js';
const window=new Window({url:'https://mdsnmchll.com/tarot.html'});window.document.body.innerHTML='<header class="site-header"></header>';
const context=vm.createContext({document:window.document,location:window.location,URL,URLSearchParams,FormData:window.FormData,Intl,console,config:{},cards,compare,meaning});
let script=readFileSync('../tarot-studio/accounts.js','utf8').replace(/^import .*;$/gm,'').replace('export function installAccounts','function installAccounts');
vm.runInContext(script+'\ninstallAccounts({readings:()=>[]});',context);
window.document.querySelector('.account-open').click();await new Promise(r=>setTimeout(r,20));
assert.match(window.document.querySelector('#account-message').textContent,/Accounts are being connected/);
const uid='00000000-0000-0000-0000-000000000001';
context.fakeUid=uid;
vm.runInContext(`user={id:fakeUid};client={from:()=>{const q={select:()=>q,eq:()=>q,maybeSingle:()=>Promise.resolve({data:{username:'test',display_name:'<img src=x onerror=alert(1)>',bio:'x',is_public:true}}),order:()=>q,or:()=>q,limit:()=>q,then:fn=>Promise.resolve({data:[]}).then(fn)};return q;}};`,context);
await vm.runInContext('dashboard()',context);
assert.equal(window.document.querySelectorAll('img').length,0);
assert.equal(window.document.querySelector('input[name=display_name]').value,'<img src=x onerror=alert(1)>');
assert.match(window.document.querySelector('#account-dialog').textContent,/Private cloud journal/);
await vm.runInContext(`rows=[{id:'a',payload:{spread:'A',cards:[{id:'major-0',reversed:false}],positions:['Today']}}];shares=[{id:'b',payload:{spread:'B',cards:[{id:'major-0',reversed:true}],positions:['Today']}}];selected=['own:a','share:b'];`,context);
window.document.querySelector('[data-account=compare]').click();await new Promise(r=>setTimeout(r,20));assert.match(window.document.querySelector('#account-dialog').textContent,/Cards in common: The Fool/);
console.log('PASS: inactive config message, account dashboard rendering, escaped profile data, own/shared free comparison');window.happyDOM.abort();
