param(
  [string]$Path = "tarot-cards.json"
)

if (-not (Test-Path $Path)) { Write-Error "File not found: $Path"; exit 1 }

$json = Get-Content -Raw -Path $Path | ConvertFrom-Json
if (-not $json) { Write-Error "Failed to parse JSON"; exit 1 }

function Set-Desc([object]$card, [string]$u, [string]$r) {
  if (-not $card.description) { $card | Add-Member -NotePropertyName description -NotePropertyValue (@{}) -Force }
  $card.description.upright = $u
  $card.description.reversed = $r
}

$minor = @{
  # Wands
  awand = @{ u = 'A spark you can feel in your hands. This is the green light to start, even if you do not know every step yet. Follow the idea that makes your blood move and give it a small, real container today. Curiosity plus action beats over-planning every time. Start messy, learn out loud, and let the fire teach you what it needs next.'; r = 'The spark is there, but the kindling is damp. Maybe you are waiting for perfect conditions or scattering your energy across too many starts. Clear one tiny blocker, choose the simplest version, and light a smaller match. Progress wants friction you can actually feel, not a fantasy launch. Keep it humble, keep it moving, and let momentum dry the wood.' };
  '2wand' = @{ u = 'Big-picture thinking meets real-world planning. You can feel that there is more out there, and you are ready to stretch toward it. Pick a direction that excites you and write down one or two practical moves you will make this week. Keep your tools light, your calendar honest, and your focus steady. This is about choosing growth on purpose.'; r = 'Analysis paralysis is still a kind of stuck. If you keep redrawing the map, you never leave town. Shrink the choice, reduce the variables, and run one small test you can learn from quickly. You do not need a perfect plan to begin; you need a direction and a next step. Adjust as you go instead of waiting for certainty.' };
  '3wand' = @{ u = 'Momentum is building and your world is getting wider. Early effort is starting to pay off, and new paths are coming into view. Keep doing what works, and set up support for the bigger horizon you are moving toward. Ask for what you need, document your process, and stay curious. You are allowed to expect good things and prepare for them.'; r = 'Delays, detours, or a too-narrow view may be limiting results. Step back and check your assumptions - maybe the opportunity is one lane over. Update the plan with what you are learning instead of forcing an old route. Patience is not passive here; tweak the angle, clean up your signals, and give the outcome room to find you.' };
  '4wand' = @{ u = 'Celebrate the milestone, big or small. You built something worth gathering around, and it is okay to enjoy the stability and support. Bring in the people who helped, say the thank-yous out loud, and let your nervous system feel safe for a minute. A little joy now actually fuels the next chapter. Home base matters because it lets you roam farther.'; r = 'If the vibe feels off at home or in your group, start with the foundation. Have the honest conversation, clean the space, or reset the shared agreements. Stability grows from small, consistent fixes, not grand gestures. A little repair now prevents a bigger crack later. You deserve a base that actually supports you.' };
  '5wand' = @{ u = 'Friendly friction can sharpen you. Competing ideas, different styles, and bold opinions can all be useful when the goal is growth. Keep it playful, keep it fair, and keep it about the work, not the people. Set ground rules that make room for everyone to contribute. This is practice for bigger stages.'; r = 'Petty conflict eats momentum. If the noise is louder than the goal, step back and reset the rules of engagement. You can choose collaboration over chaos, or you can choose a new arena entirely. Protect your energy from performative battles. Not every argument deserves your best thinking.' };
  '6wand' = @{ u = 'A clean win. Take the compliment, share the credit, and let the lift carry you into your next move. Success is feedback you can bank - note what worked and repeat it with intention. Celebrate without drifting into complacency. Confidence grows from clear evidence and steady follow-through.'; r = 'Chasing applause instead of progress is a trap. If you are optimizing for likes or optics, the work will thin out. Return to substance: what outcomes matter, what values guide you, and what standard do you hold. Your best wins are the ones you can stand behind, not just stand in front of.' };
  '7wand' = @{ u = 'Hold your ground without hardening your heart. You worked for this view, and it is okay to defend it with calm, clear boundaries. Say what you will and will not do, then stick to it. You do not have to fight everyone; you do have to stay aligned. Strength here is steady, not loud.'; r = 'Being on guard all the time is exhausting. If you are defending everything, you are protecting nothing. Choose the hills that actually matter and let the rest go by. Invite support, rest your shoulders, and remember that being right is different from being well. Save your energy for the real stand.' };
  '8wand' = @{ u = 'It is moving fast - in a good way. Clear your runway, send the message, and ride the current while it is strong. Direct, timely communication will keep everyone pointed the same way. When momentum and clarity agree, amazing ground gets covered. Keep it simple and keep it honest.'; r = 'Mixed signals and rushed actions scatter results. Slow the pace just enough to aim, then take one coordinated shot instead of six half-sent ones. Tighten the message, trim the extras, and choose the channel that actually reaches your people. Speed is helpful when direction is real. Make direction real.' };
  '9wand' = @{ u = 'You are tired and still here, which says a lot. Protect the ground you have gained and set boundaries that guard your effort. Rest in cycles, plan shorter pushes, and remember why you started. Resilience is not about grinding forever; it is about recovering well enough to try again. You can finish this.'; r = 'Running on fumes turns every task into a hill. Step back, refill, and ask for help before you need it. Your body is part of the project plan, not an afterthought. Shorten the list to what actually matters this week and let the rest wait. You will move farther once you have energy again.' };
  '10wand' = @{ u = 'There is a lot on your shoulders. If it truly matters, keep going - but also look for what you can delegate, delay, or drop. Structure the load so it does not own you: simpler tools, clearer priorities, more honest timelines. Busy does not always equal meaningful. Carry what is yours and set the rest down.'; r = 'You may be hauling more than is necessary or healthy. Perfectionism and people-pleasing add invisible weight. Recut the commitment into something a human can do, and ask for backup where it counts. A lighter load will not make you less worthy - it will make you more effective. Choose sustainable over heroic.' };
  'pwand' = @{ u = 'Fresh spark, open road. Follow your curiosity and make something small and real today - a draft, a message, a test run. Treat this as an adventure and expect to learn as you go. Enthusiasm is a resource; spend it on action, not debate. Small beginnings compound fast when you keep showing up.'; r = 'You might start strong and then fade, or bounce from idea to idea before anything sticks. Give your spark a simple container - time on the calendar, a clear scope, a buddy to check in with. Let constraints be creative. Follow-through is a skill, and you can practice it in tiny, friendly ways.' };
  'nwand' = @{ u = 'Bold, fast, a little wild. When you aim the heat at a real target, you cover serious ground. Let passion pull you forward, and keep one eye on the map so you do not waste the sprint. Courage is contagious; your movement gives others permission to move too. Go make a dent.'; r = 'All gas, no map means impressive motion with fuzzy results. Slow half a beat to aim and you will actually hit something. You do not need to cool off - you need a purpose big enough to hold your speed. Choose the mission, then light it up with the same fire.' };
  'qwand' = @{ u = 'Warm charisma and creative presence. You do not fake sunshine - you generate it by being fully yourself. Lead by inviting people in, giving them room to shine, and modeling healthy confidence. Joy is practical; it makes the work easier to do. Keep your boundaries bright and your humor handy.'; r = 'The smile is bright but the tank may be empty. You do not have to set yourself on fire to keep the room warm. Share the spotlight, share the workload, and let people help because they want to. Real leadership includes knowing when to rest.' };
  'kwand' = @{ u = 'Vision plus execution. You spot the opportunity, rally people around it, and take responsibility for the outcome. Make the call, explain the why, and move first. Courage grows trust, and trust multiplies results. This is what it looks like to lead from the front.'; r = 'Command without connection falls flat. If you want commitment, invite input, listen for what you missed, and then decide. People will run with you when they feel seen and respected. Authority is strongest when it serves the mission and the humans doing it.' };

  # Cups
  acup = @{ u = 'Heart online. This could be new feelings, a fresh connection, or creative flow that feels honest and easy. Let it be simple instead of trying to name it from every angle. Follow what feels nourishing and safe, and add one small ritual that keeps the channel open. You do not have to brace for the other shoe; let good be good.'; r = 'Either the walls are too high or the feelings are everywhere. Name one thing you feel to one safe person, and let that be enough for today. If you are overwhelmed, lower the input and raise the care. If you are numb, try a tiny act of kindness toward yourself and see what moves. The goal is not dramatic catharsis - it is connection you can actually hold.' };
  '2cup' = @{ u = 'Mutual interest, low-ego connection, and easy reciprocity. This can be romance, friendship, or a good creative partner - it all starts with honest presence. Keep the pace natural and let clarity grow from conversation, not guessing. When both people bring care and self-respect, the middle gets very strong. Choose to show up like that.'; r = 'Chemistry without clarity makes a mess. If something feels off, check expectations and timing before the story writes itself. Name what you want in simple terms and ask the other person to do the same. Alignment beats spark long-term. If it is a no, let it be a kind no and move on.' };
  '3cup' = @{ u = 'Friends, laughter, group wins, and easy celebration. Make space for joy that does not require a reason, and share good news without apologizing. Showing up for each other is the point; the party is the excuse. Let community refill your battery and remind you you are not doing life alone. Connection is medicine.'; r = 'Too much of a good thing can tip into FOMO or burnout. If the calendar is crowded but your heart feels thin, choose presence over performance. Smaller, real moments beat big, blurry ones. Say no when you need to so your yes stays sincere. Your people want the real you, not the depleted one.' };
  '4cup' = @{ u = 'A meh mood is not a moral failing. You might be bored, full, or just in need of a reset. Try a small change - a walk, a different playlist, a new recipe - or take a quiet day to let your mind settle. Often the spark returns once you stop forcing it. Let the pause do its work.'; r = 'Apathy that lingers turns into avoidance. Shake the snow globe a bit: move your body, change the scene, or say yes to one tiny invite you would usually skip. Momentum does not need to be big to be real. Start where you are, not where you think you should be.' };
  '5cup' = @{ u = 'Real grief, real disappointment. Let yourself feel it without rushing the lesson. When the first wave eases, look for what is still standing and who is still with you. Loss carves space for new honesty. You can carry it and still move.'; r = 'Replaying the worst parts keeps you in the loop. Gently turn toward one doable kindness - to yourself or someone else - and let that be the first stitch of repair. You do not have to be over it to take a step forward. Healing is made of small, repeated choices.' };
  '6cup' = @{ u = 'Sweet nostalgia and simple kindness. Remember what used to light you up and bring a small piece of it back into today. Reach out to someone from your roots or create a tradition that feels like home. Let comfort be creative. Soft does not mean stuck.'; r = 'Living in the highlight reel keeps you from the life in front of you. Keep the memory, but update the story with who you are now. Honor the past by building something present. The best parts of then can inform a better version of now.' };
  '7cup' = @{ u = 'So many options, all sparkling. Enjoy the dreaming phase, then pick one real path and test it in the light of day. Limit the menu on purpose so your choice gets the attention it deserves. Fantasy is great inspiration; action is how you learn what you actually want.'; r = 'Fog and wishful thinking blur the way. Ground your decision in one fact you can verify and one small experiment you can run. If a story only works in your head, it is not ready yet. Bring your imagination with you, just add evidence.' };
  '8cup' = @{ u = 'Walking away can be an act of respect - for yourself and the thing you are leaving. When it is not feeding you, leaving is growth. Go with honesty, keep the drama low, and let the empty space stay empty for a bit. The new path needs room to arrive.'; r = 'Avoiding the goodbye drags out the ache. Be kind and be clear, even if your voice shakes. Your energy will thank you on the other side. Closure is not a door slamming; it is you choosing a direction and taking it.' };
  '9cup' = @{ u = 'A wish arriving, a moment of real contentment. Let yourself enjoy it without apology, and notice how satisfaction feels in your body. Use that feeling as a north star for future choices. Joy is not a finish line; it is fuel. Share it, savor it, and keep going.'; r = 'It looks good on paper but feels thin in your chest. Retune your goals toward what actually nourishes you, not what impresses people you do not even like. Swap a couple shoulds for wants and see what changes. Real contentment is quiet and sturdy.' };
  '10cup' = @{ u = 'Belonging shows up as ease. Family - chosen or given - feels aligned, and everyday life has moments of simple rightness. Name the good out loud, and do small things that keep the connections strong. Happiness does not need to be grand to be true. Protect what makes this feel like home.'; r = 'Surface smiles with an undercurrent of stress can happen anywhere. Talk about the tension early and kindly so it does not calcify. Choose repair over perfection, and let everyone be human. Little truths keep the roof solid.' };
  'pcup' = @{ u = 'Good news, a sweet crush, or a creative ping. Lead with curiosity and let small, sincere gestures carry your message. You do not need clever - you just need honest. Stay open, keep it gentle, and let things unfold at their natural pace.'; r = 'Over-idealizing, mixed messages, or avoiding the real talk. Keep it specific and kind so no one has to guess what you mean. If your hopes are doing all the communication, slow down and check in with reality. Softness and clarity can coexist.' };
  'ncup' = @{ u = 'Romantic and creative motion. Follow the feeling and keep your feet on the ground, balancing poetry with plans. Express yourself, make the gesture, and stay responsive. Heart-led does not mean headless. Your sincerity is a strength.'; r = 'Charm without consistency leads people in circles. Say what you mean, move at a pace you can keep, and match your words with action. If it is not a yes, do not sell it like one. Being clear is kinder than being impressive.' };
  'qcup' = @{ u = 'Steady heart and strong intuition. You can hold space without holding it all. Boundaries make your care sustainable and your presence effective. Listen deeply, act kindly, and let your empathy have edges. This is emotional leadership.'; r = 'Taking on everyone else''s weather is not the job. Protect your energy, name your limits, and step back when you start to blur. Your care goes farther when you are resourced. Let others carry their part of the sky.' };
  'kcup' = @{ u = 'Calm in the deep end. Emotional leadership looks like steadiness, perspective, and the courage to stay present. You do not need to fix everything to be helpful. Model grounded responses and people will mirror you. This is how rooms de-escalate.'; r = 'Bottled-up or moody under the surface. Share what is true before it leaks sideways, and ask for what helps. Regulate first, then communicate. You get to be human and in charge at the same time.' };

  # Pentacles
  apent = @{ u = 'A real-world green light. New work, money, home, or health habit that could actually stick. Keep it practical and small so you can repeat it. Track your progress, celebrate tiny wins, and watch the foundation thicken. Reliable is exciting when you can feel it working.'; r = 'Delays or shaky ground are not the end; they are data. Tighten the plan, check your resources, and try again with one tweak. If you are forcing it, step back and rebuild the basics. Patience and consistency are compounding interest.' };
  '2pent' = @{ u = 'You are juggling a lot and doing okay. Keep it light where you can, use a list to brain-dump the noise, and move one piece at a time. Let your schedule reflect your actual capacity, not the imaginary kind. Balance comes from boundaries and small adjustments.'; r = 'Too many plates leads to broken ones. Drop the least important on purpose, automate what you can, and ask for help where it matters. Busy is not a personality. You are allowed to choose ease.' };
  '3pent' = @{ u = 'Teamwork that actually works. Clear roles, shared standards, and kind feedback make the build solid. Ask for help where someone is stronger and offer yours where you shine. Pride in craft is contagious. Make something you are proud to sign.'; r = 'Roles unclear, standards fuzzy, or feedback missing. Define done together and decide how you will know you are on track. A short check-in saves a long rework. Collaboration is a skill; practice it openly.' };
  '4pent' = @{ u = 'Stability is a worthy goal. Save a little, tidy your systems, and cover your basics so your nervous system can breathe. Security does not make you boring; it makes you brave. Build a base you can launch from.'; r = 'Clutching tight squeezes the life out of growth. Loosen the grip a notch and let circulation return - to money, time, and trust. You can be responsible and generous at the same time. Holding everything forever is not the only way to feel safe.' };
  '5pent' = @{ u = 'Tough season, but not a verdict. Ask for help and take the help without apology. There are resources and people who actually want to show up for you. You are not a problem to be solved; you are a person to be supported. Keep moving one honest step at a time.'; r = 'Isolation makes it colder. Step toward community, services, or one steady friend sooner than is comfortable. Shame hates daylight; let a little in. You are allowed to need things and still respect yourself.' };
  '6pent' = @{ u = 'Giving and receiving with balance. Share what you have, accept what you need, and keep dignity at the center of the exchange. Generosity goes farther when it respects boundaries. Make support a two-way street.'; r = 'Strings attached, uneven scales, or giving that breeds resentment. If it is not mutual, reset the terms or step back. Help that harms your own stability is not help. Try clear agreements and honest limits.' };
  '7pent' = @{ u = 'Pause and check the garden. Progress is slow and still real, especially with long-haul goals. Adjust the plan, keep tending, and let time do its job. Patience can be active: small improvements add up. Trust the process you can see.'; r = 'Impatience makes you dig up seeds to see if they are growing. Set a timeline, define meaningful milestones, and hold yourself to those instead of fantasy deadlines. If the plan is weak, improve it. If it is strong, let it work.' };
  '8pent' = @{ u = 'Reps and craft. Show up, improve tiny details, and let consistency build your confidence. Mastery is boring up close and beautiful from a distance. Document what you learn so future-you can move faster. Pride in process becomes pride in results.'; r = 'Busywork and perfection loops look productive but do not move the needle. Focus on the one skill that would change everything if it got 20 percent better. Ship small updates instead of polishing in private forever. Momentum beats immaculate.' };
  '9pent' = @{ u = 'Competence pays off. Enjoy the independence you built and treat yourself like someone you respect. Make time to actually enjoy the life your effort created - a walk, a nice meal, a slow morning. Self-trust is luxury. Wear it.'; r = 'Self-sufficiency turning into lonely is a common trap. You can keep your standards and still ask for company or support. Let people in where it matters. Independence is stronger with a little interdependence.' };
  '10pent' = @{ u = 'Long game wins. Think legacy, stability, and shared resources that outlast a season. Invest in systems and relationships that support more than just you. Take pride in being a good ancestor. Solid foundations make generous futures.'; r = 'Tradition without flexibility turns brittle. Keep what works, update what does not, and make room for the next generation''s way. Stability that refuses to evolve eventually cracks. Choose living structure over static rules.' };
  'ppent' = @{ u = 'Beginner mind at the bank of real life. Learn by doing, take notes, and track small progress you can see. Ask the practical questions and try the practical answers. It adds up quickly when you keep it simple. Curiosity is a savings plan.'; r = 'Stuck in planning is still stuck. Pick one tiny experiment with a clear next step and a short feedback loop. You can always refine after reality has weighed in. Momentum belongs to the starters.' };
  'npent' = @{ u = 'Steady, thorough, dependable - boring in the best way. Keep going exactly like this. Your care shows in the details and it lasts. People trust what you build because you do not cut corners.'; r = 'Stalled out, overcautious, or buried under the to-do list. Break the task into smaller pieces, move one across the line, and let that win pull the next one. Progress can be quiet and still count.' };
  'qpent' = @{ u = 'Grounded care and practical comfort. You make spaces feel safe and projects feel doable. Think warm meals, clear budgets, and plans that include rest. This is leadership through hospitality and competence. Keep your own tank filled too.'; r = 'Overgiving or micromanaging steals your calm. Trust others with real responsibility, delegate clearly, and take your hands off. Your value is not measured in exhaustion. Choose sustainable care.' };
  'kpent' = @{ u = 'Responsible leadership that builds systems people actually want to work in. You measure what matters, invest in people, and think long-term. Results are steady because your values are steady. Keep modeling dignity and discipline.'; r = 'Control without mentorship caps growth. Teach what you know, open doors, and share the wins. Authority grows when it multiplies other people''s competence. Leave the place better than you found it.' };
}

foreach ($id in $minor.Keys) {
  $card = $json | Where-Object { $_.id -eq $id }
  if ($null -ne $card) {
    Set-Desc -card $card -u $minor[$id].u -r $minor[$id].r
  }
}

$json | ConvertTo-Json -Depth 10 | Out-File -Encoding UTF8 -FilePath $Path
Write-Host "Customized minor arcana (Cups, Wands, Pentacles) with longer, casual paragraphs."

